spring.config.active.on-profile=dev

spring.sql.unit.mode= always


# MySQL Database Configuration
# In-memory database (data lost on restart - perfect for quick dev/testing)
spring.datasource.url=jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;MODE=MySQL;INIT=CREATE SCHEMA IF NOT EXISTS devdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Enable H2 web console → http://localhost:8080/h2-console (or your port)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.flyway.clean-disabled=false
spring.h2.console.settings.web-allow-others=true
server.port=${PORT}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.docker.compose.enabled=true

# Optional: if you have data.sql / schema.sql in resources, run them automatically
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
