spring.config.active.on-profile=dev

spring.sql.unit.mode= always
spring.flyway.clean-disabled=false


# MySQL Database Configuration
spring.datasource.url=${SUPABASE_URL}

spring.flyway.clean-disabled=false

server.port=${PORT}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.docker.compose.enabled=true
