spring.application.name=AA

spring.docker.compose.file=src/main/resources/compose.yaml
logging.level.org.springframework.boot.docker.compose=DEBUG
spring.docker.compose.lifecycle-management=start_only
spring.threads.virtual.enabled= true




# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.open-in-view=false